### ISSUE TITLE
capabilities : os version - not constant

### ISSUE THREAD

**Issue by padamCZ** [jaroslavpsenicka/bscapp#5]
Ve spoustecim dialogu na karte "Scenare" nemenim nic a presto OS verze neni dodrzena 
(viz. browserstack history).
Podezreni:  capabilities se skladaji pro kazdy beh extra, 
**ale neobsahuji** `os, os_version, browser_version, resolution`.

**Comment by jaroslavpsenicka** [comment]
'os': 'Windows',
'os_version': '10',
'browser_version': '73.0 beta',
'resolution': '1920x1200'

**Comment by jaroslavpsenicka** [comment]
tedy OK?

**Comment by padamCZ** [comment]
ok
