### ISSUE TITLE
implementovat vyplnovani dropDown ve spoustecim dialogu na zaklade : rest-api-browsers

### ISSUE THREAD

**Issue by padamCZ** [jaroslavpsenicka/bscapp#8]
https://www.browserstack.com/automate/rest-api#rest-api-browsers

**Comment by jaroslavpsenicka** [comment]
struktura JSONu je tato:

```
{
   "os": "Windows",
   "os_version": "XP",
   "browser": "opera",
   "device": null,
   "browser_version": "12.15",
   "real_mobile": null
}
```

celkem 1476 záznamů.

**Comment by jaroslavpsenicka** [comment]
zatím funguje načtení seznamu os a os_version
jak by měl fungovat zbytek
- měl by se filtrovat seznam browserů podle vybraného os_version?
- měla by být volba verze prohlížeče jako listbox namísto současnýho textfieldu?

Pak by teda volba musela probíhat takto:
```
OS > OS version > Browser > Browser version
```

Zatím je Browser a jeho verze nezáislá. A ano, umožňuje to zvolit nevalidní kombinaci.
Ale hej! Tohle není aplikace pro pomocnou školu.

Tak jak?

**Comment by padamCZ** [comment]
Je to OK.
DONE.
